fastly/insights.js

src/scout.js
This fixes the `cutsTheMustard` feature detection test within the initialisation of the scout.js file. It seems this was incorrectly optimised by Prettier when porting the codebase. This is to prevent the script running on older browsers and ensures a runtime exception doesn't bubble up to the parent page.
=> Fix the cuts-the-mustard test in scout.js

src/scout.js, test/scout.spec.js
Adds a guard around the initialisation of the library inside the scout file to ensure that the library has been loaded and the method exists before trying to invoke it.
Resilience. The networking for the library may have failed, the library may have error during paring etc. This ensures we don't throw an error to the parent page.
Thank you to @dennismartensson for reporting the issue.
=> Guard library initialisation in failure modes 

src/tasks/pop/index.js
Refactors the promise chain logic within the POP task to ensure exceptions thrown from the resource-timing `asyncGetEntry()` function don't bubble as uncaught. 
We have observed a large number of uncaught exceptions being reported by user-agents with the error message `Timed out observing resource timing` which is thrown by the [`src/lib/resource-timing.js`](https://github.com/fastly/insights.js/blob/master/src/lib/resource-timing.js#L8-L35) library. As the invocation of this promise was called before being used the error may happen before the later `catch()` exception handler was attached to the chain. Thus causing the error to bubble to the parent document. 
Refactoring the promise logic in the calling task will ensure the exception is appropriately caught and handled by the task …
=> Fix resource-timing race causing an uncaught promise exception 

karma.conf.js, package.json, test/scout.spec.js, yarn.lock
Attempt to make the CI cross-browser unit-test runs via Karma and Saucelabs more stable by increasing disconnect, timeout and retry settings.
The upstream CI job has recently become very flaky due to network or browser image startup issues between Travis CI and SauceLabs. Which 99% of the time are false negatives and thus are very frustrating as they require manual interaction to retry the build multiple times until they pass. 
This is an an attempt to fix that.
=> Update karma settings

config.js, src/runner.js, test/runner.spec.js
Move the `hosts` configuration object out of the global `config.server` object and into the `config.settings` object. So the path is now `config.settings.hosts`.
Since #6 we have been incorrectly sending the `hosts` data along with every beacon as it was in the `config.server` object which contains other useful data required for analysis such as `server.datacenter`. This correctly separates the concerns by moving the data to settings, which is the correct classification.
=> Move hosts configuration out of server object and into settings object

src/util/sequence.js
Replaces the implementation of the `util/sequence.js` with a correctly functioning implementation.
The existing implementation didn't behave as desired and was queuing the beacons to be sent once all tasks were complete rather than once each task is complete. This therefore may increase the amount of beacons we receive for clients which may be closing/navigating before all tasks have complete.
=> Replace Promise sequence implmentation

scripts/build.js, src/lib.js, src/runner.js, src/scout.js
Refactors the build process and application initialisation to ensure we don't overwrite any existing objects on the `window.FASTLY` global.
It's good 3rd party practice to not mutate existing objects. We also need this functionality for the new website demo application, to allow the `window.FASTLY.results` array to be shadowed by a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) object to observe and display results.
=> Refactor bundle output iife

yarn.lock
Upgrades dev dependency `rollup-plugin-node-resolve` used for project compilation as it was causing a breaking error in environments using Node v10.
Node v10 has changed `Object.readFile()` which the dependency uses, as is throwing this error:
```
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes.
```
Which is preventing developers and CI from uprgading to v10.
=> Bump version of rollup-plugin-node-resolve

README.md, config.js, scripts/build.js, src/tasks/fetch/index.js, src/tasks/index.js, src/tasks/pop/index.js, src/util/prefix-keys.js, test/tasks/fetch.spec.js, test/tasks/pop.spec.js, test/util/prefix-keys.spec.js
Adds a new task type `fetch`, which is nearly identical to the existing `pop` task. This fetches a single object on a Fastly Insights owned hostname matching `*.fastly-insights.com` For experimentation and diagnostic purposes.
We want to be able to compare timing from existing endpoints against new experimental 
so we can track their effectiveness. By performing this test on client runs it allows us to easily do this comparison. 
Create a single task which will only be run once per client to fetch an object from the Fastly Insights hostname such as `pdata.pops.fastly-insights.com` and record the datacenter which served the object and the associated resource timing information.
- Abstract the object `prefixKeys` logic shared between both tasks to a utility library
- Add `fetch` task and …
=> Add new fetch task

src/tasks/task.js, test/tasks/task.spec.js
Adds `task_id` property to the task result model to ensure it gets sent as part of the beacon payload for all tasks. 
This seems to have been missed originally as has always been documented as part of the task schema, however hasn't been an issue as we've only had one task type `pop`. As we introduce new task types such as `fetch` (see #18) we need a way to filter and query the beacon data by their `task_type` and unique `task_id` properties.
=> Add task_id to base task result model

jest.config.js, package-lock.json, src/@types/index.d.ts, src/@types/worker.d.ts, src/__mocks__/worker.ts, src/index.spec.ts, src/index.ts, src/util/loadWhenDocumentReady.spec.ts, src/util/loadWhenDocumentReady.ts, src/util/object.spec.ts, src/util/object.ts, src/worker.spec.ts, webpack.common.js
Reimplements the [scout file](https://alexsexton.com/blog/2013/03/deploying-javascript-applications/) loading pattern to `index.ts` which is very similar to what we have in v1. We test for browser feature support and if it passes, we invoke the `init()` method which loads the WebWorker main library when the browser is ready.
- I've tried to abstract the main buisness logic utility functions out of the index file into their own modules to keep it clean and aid testability
- We need the feature detection logic to work on all browsers, hence the util and not simply using `Object.hasOwnProperty()`
- Had to do some pretty gnarly mocking and type casting to be able to test the `init()` method, as we don't run webpack for unit tests …
=> [v2.0.0] Implement scout loading pattern

src/util/promiseRetry.spec.ts, src/util/promiseRetry.ts
Adds a utility function to retry a promise `n` times with a delay of `m` ms in-between each invocation. This will be used to retry tasks or individual fetch requests etc.
Due to the way the recursion works and how `setTimeout` is natievly mocked in Jest, i've had to do some hackery with the micro task queue to get the test working properly. But it works! See this SO answer from the Jest team for more detail: https://stackoverflow.com/a/51132058
```js
import retry from './util/promiseRetry';
const retryDelay = 100;
const retryAttempts = 3;
const getConfig = () => fetch(url).then(r => r.json());
return retry(getConfig, retryAttempts, retryDelay)
```
=> Add promise retry utility

.babelrc, jest.config.js, src/@types/index.d.ts, src/@types/worker.d.ts, src/constants.ts, src/index.ts, src/util/promiseRetry.ts, src/util/scriptQueryParameters.spec.ts, src/util/scriptQueryParameters.ts, src/worker.spec.ts, src/worker.ts, webpack.HtmlApiTokenWebpackPlugin.js, webpack.common.js, webpack.dev.js, webpack.prod.js
Adds utilities to parse the API token from the script tag `src` url and pass to `Worker.init()` to fetch the config from API. 
As we are no longer dynamically transcluding the API token into the JavaScript at the edge (thus allowing for the same script for all consumers), we need to obtain it from the script tag, i,.e. from `<script defer src="https://www.fastly-insights.com/insights.js?k=1-2-3-4"></script>`. Therefore we have to use a utility to find the tag and parse out the parameters. 
- Due to browser support and the size of the polyfill, we can't just use the newer URL interface: `let params = (new URL(src)).searchParams;` and have opted for writing a custom util. …
=> Fetch config with API token

webpack.prod.js
**⚠️ Note this is a PR into the v.2.0.0 branch and not master**
Sets the correct public asset path for webpack in production.
=> Production `publicPath`

jest.config.js, package-lock.json, package.json, src/__mocks__/worker.ts, src/index.spec.ts, src/index.ts
Due to the cross-origin loading restrictions of `WebWorkers` this refactors the scout script to load the worker library as a normal synchronous module inline, instead of instantiating a new `WebWorker` with the library. This is hopefully a temporary measure until we can iron out the related issues. 
I was unaware of the tighter same-origin restrictions of WebWorkers, regardless of CORS headers or the normal cross-origin rules within browsers. Therefore, when v2.0.0 of the library was loaded as a 3rd party we were observing errors stating the worker was prevented from loading due to cross-origin restrictions.
It is possible to load cross origin web workers via an inline `Blob` URL, such as  `new Worker(URL.createObjectURL(new …
=> Load worker as a normal synchronous module

src/constants.ts, src/util/scriptQueryParameters.spec.ts, src/util/scriptQueryParameters.ts, src/worker.ts
**⚠️ Note this is a PR into the v.2.0.0 branch and not master**
Refactors the worker configuration initialisation to read config hostname from script tag in production and pre-production environment.
=> Refactor worker config initialisation

src/@types/index.d.ts, src/fixtures/config.ts, src/lib/filterTasksByClientClassification.spec.ts, src/lib/filterTasksByClientClassification.ts, src/worker.ts
Refactors the task running logic to initially filter tasks by their `classification` property comparing against the current client's classification. I.e. enables the library to only run tasks on a given connection type in a given network. For example this task would only run on the ASN `5089` in USA, Great Britain and Germany. 
```js
{
id: "test",
type: "fetch",
resource: "https://test.fastly-insights.com/o.svg",
weight: 1,
req_header: "",
resp_header: "",
classification: {
country_code: ["GB", "US", "DE"],
asn: [5089]
}
}
```
=> Task classification

src/lib/templateResource.spec.ts, src/lib/templateResource.ts, src/tasks/task.ts
This allows the task resources returned from the API to contain template placeholder substrings, such as `<% TEST_ID %>`, which get replaced with a real value at execution time. This is useful to encode dynamic properties such as the test ID or a random string in the request URL for cache busting or correlation purposes.
=> Support template string placeholders in the task.resource URL field

src/@types/index.d.ts, src/index.ts
*⚠️ Note this is a PR into the v.2.0.0 branch and not master*
Exposes the final results array to the window global `FASTLY`. This follows the same conventions in master/v1 of the library. The results array is mainly exposed for debugging purposes, however we also use this array to implement the https://insights.fastlylabs.com/test page, as it uses a `Proxy` assigned to the global to listen to new results and visualise in the UI.
=> Expose results to FASTLY global

src/worker.ts
Use the `https://fastly-insights.com` apex hostname for the config API request. This allows us to set a  single [Network Error Logging](https://www.w3.org/TR/network-error-logging/) policy that will apply to all subdomain's of the domain.
=> Use the fastly-insights.com apex for the config API request

src/worker.ts
This fixes a bug introduced in #50 in which we were using the apex hostname for all environments. Now we only use the apex if the script host is `www.` and fallback to using the script host in other environments.
=> Fix the config API hostname in pre-production environments

README.md
The project has kindly been approved for free open source cross-browser testing from SauceLabs, a requirement of which is to have this badge to give credit to Sauce Labs for their support. Which we will very happily do 😄  
I will be following up with some further PRs to introduce a small E2E test suite using Sauce Labs.
=> Add Sauce Labs Open Sauce testing support badge to README.md

package-lock.json, package.json
Bumps [`@fastly/perfromance-obsever-polyfill`](https://github.com/fastly/performance-observer-polyfill) to fix a spec compilance bug, further information in: https://github.com/fastly/performance-observer-polyfill/pull/10. Also took the liberty of running `npm audit fix` to fix some low vulns and pick up new deps.
=> Bump @fastly/perfromance-obsever-polyfill to v1.1.1

src/index.ts
I missed this in the v3  migration (#62), the return value from the Open Insights `init()` method is a [`TestResultBundle[]`](https://open-insights-docs.edgecompute.app/interfaces/__types_index_.testresultbundle.html) and not beacon object which it previously was. This has subsequently broken the test application at https://insights.fastlylabs.com/test as it assumes a different data structure. Therefore the solution is to map the result to the beacon object.
=> Ensure the actual beacon result is returned and not the TestResultBundle

package-lock.json, package.json
Bumps [open-insights-provider-fastly](https://github.com/fastly/open-insights-provider-fastly) to 1.0.1 which ensures the resource timing server-timing property is included in the beacon payload.
=> Bump open-insights-provider-fastly to v1.0.1
